### ISSUE TITLE
two round shape apears.

### ISSUE THREAD

**Issue by sagarmaiyad** [albinmathew/PhotoCrop#1]
i am using your demo. there is showing two circular shape box for croping and when i click on send button, it crops in rectangle. can i get rectangle crop box rather than circular.?

**Comment by albinmathew** [comment]
@Slake07 
In the CropOverlayClass replace the on Draw with this 

```
@Override
    protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);
        setLayerType(View.LAYER_TYPE_SOFTWARE, null);
        final float radius = TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, CORNER_RADIUS, mContext.getResources().getDisplayMetrics());

        RectF rectF = new RectF(Edge.LEFT.getCoordinate(),
                Edge.TOP.getCoordinate(),
                Edge.RIGHT.getCoordinate(),
                Edge.BOTTOM.getCoordinate());
        Path clipPath = new Path();
        clipPath.addRoundRect(rectF,radius,radius, Path.Direction.CW);
        canvas.clipPath(clipPath, Region.Op.DIFFERENCE);
        canvas.drawARGB(204, 41, 48, 63);
        canvas.restore();
        canvas.drawRoundRect(rectF,radius,radius,mBorderPaint);
        drawRuleOfThirdsGuidelines(canvas);
    }
```

changes are  `clipPath.addRoundRect(rectF,radius,radius, Path.Direction.CW);` and `canvas.drawRoundRect(rectF,radius,radius,mBorderPaint);`
uncomment `drawRuleOfThirdsGuidelines(canvas);` to draw guidelines

**Comment by albinmathew** [comment]
@Slake07  is there showing two circular shape box for cropping ?? can you please attach a screen shot. the library is under development. All suggestions are welcomed.

**Comment by sagarmaiyad** [comment]
This is first image:

![device-2015-06-26-181746](https://cloud.githubusercontent.com/assets/3199539/8377560/ec8be22c-1c2f-11e5-9a68-33997aadd51e.png)

after crop:

![device-2015-06-26-181758](https://cloud.githubusercontent.com/assets/3199539/8377574/03d0033c-1c30-11e5-81ca-adb8c22fca46.png)

**Comment by albinmathew** [comment]
Actually the crop is happening for the rectangular region bounding the circle. I have created it for a specific requirement. We can crop circular area also. Can you please post your onDraw() method and your device version. I couldn't reproduce the error.

**Comment by sagarmaiyad** [comment]
i just use your code. nothing else. and i am using motorola moto g and moto e. and i want rectangular region. can you help me with that.?

**Comment by sagarmaiyad** [comment]
if i used your above code for rectangle box then it show something like below:

![device-2015-06-26-185814](https://cloud.githubusercontent.com/assets/3199539/8378238/97a71c76-1c35-11e5-83c2-2fcdfc0315e9.png)

**Comment by albinmathew** [comment]
@Slake07 I will look at the issue soon and will find a solution for your requirement

**Comment by albinmathew** [comment]
@Slake07  Have you got the issue fixed ?

**Comment by sagarmaiyad** [comment]
no, i was waiting for your reply as u said.

**Comment by albinmathew** [comment]
@Slake07 I  have updated the library and its working fine
