### ISSUE TITLE
PhotoView setScaleType doesn't take effect

### ISSUE THREAD

**Issue by NtcWai** [albinmathew/PhotoCrop#3]
![screen shot 2015-08-17 at 17 04 16](https://cloud.githubusercontent.com/assets/1621221/9302671/9da771c0-4502-11e5-94f3-ad12d3e78eda.png)

**Comment by cuagia** [comment]
![screen shot 2015-08-17 at 17 07 20](https://cloud.githubusercontent.com/assets/1621221/9302701/ca1782ea-4502-11e5-850f-44dbaf814927.png)

**Comment by NtcWai** [comment]
![screen shot 2015-08-17 at 17 08 16](https://cloud.githubusercontent.com/assets/1621221/9302715/f057bc40-4502-11e5-8053-cecd66c2f562.png)

**Comment by albinmathew** [comment]
@cuagia PhotoView sets it's own ScaleType to Matrix, then diverts all calls setScaleType to this.setScaleType automatically. So setting scale type wont  affect your layout.

**Comment by cuagia** [comment]
How can I accomplish it ?
Please :)

**Comment by albinmathew** [comment]
@cuagia  you can center the image by 
`android:scaleType = center`

**Comment by NtcWai** [comment]
Thank you very much.
After reading the code at ImageCropActivity in your sample project, I find out it worked well when call all them below:

`android:scaleType = center`

```
mImageView.addListener(new PhotoViewAttacher.IGetImageBounds() {
            @Override
            public Rect getImageBounds() {
                return new Rect((int) Edge.LEFT.getCoordinate(), (int) Edge.TOP.getCoordinate(), (int) Edge.RIGHT.getCoordinate(), (int) Edge.BOTTOM.getCoordinate());
            }
        });
```

```
private void init() {
        Bitmap b = getBitmap(mImageUri);
        Drawable bitmap = new BitmapDrawable(getResources(), b);
        int h = bitmap.getIntrinsicHeight();
        int w = bitmap.getIntrinsicWidth();
        final float cropWindowWidth = Edge.getWidth();
        final float cropWindowHeight = Edge.getHeight();
        if (h <= w) {
            minScale = (cropWindowHeight + 1f) / h;
        } else if (w < h) {
            minScale = (cropWindowWidth + 1f) / w;
        }
        mImageView.setMaximumScale(minScale * 3);
        mImageView.setMediumScale(minScale * 2);
        mImageView.setMinimumScale(minScale);
        mImageView.setImageDrawable(bitmap);
        mImageView.setScale(minScale);

    }
```
