### ISSUE TITLE
Unable to build when using proguard

### ISSUE THREAD

**Issue by andrei-cimpan** [albinmathew/PhotoCrop#5]
The library is using sqrt() method that is deprecated in API 23, so ProGuard throws a warning:

```
Warning: com.albinmathew.photocrop.photoview.PhotoViewAttacher: can't find referenced method 'float sqrt(float)' in library class android.util.FloatMath
Warning: com.albinmathew.photocrop.photoview.gestures.CupcakeGestureDetector: can't find referenced method 'float sqrt(float)' in library class android.util.FloatMath 
```

For now we can use the _dontwarn_ option, but it would be great to fix these

**Comment by albinmathew** [comment]
Which version of library are you using,? Please change to new library version 1.0.3

**Comment by andrei-cimpan** [comment]
yes, it's 1.0.3. This is what the build.gradle contains related to your library: 

```
compile 'com.albinmathew:photo-crop-library:1.0.3'
```

**Comment by albinmathew** [comment]
I have changed the sqrt() from the code on upgrading the version, but I guess I may not have changed the code reference in comments, Let me check it. Anyways thanks for letting me know.

**Comment by andrei-cimpan** [comment]
OK. You're welcome. Thanks for the great library!

**Comment by Morteza-Rastgoo** [comment]
same issue on 1.0.3
any update?
